### ISSUE TITLE
Links to YouTube videos?

### ISSUE THREAD

**Issue by georgescharlesbrain** [sui-foundation/encode-sui-educate#1]
Where can I find the links to the YouTube videos?
Based on my research, they are currently hidden somewhere in the Discord group.
It would be nice to have them in your repo, next to the slides.

**Comment by shayansanjideh** [comment]
You can find all YouTube videos via the Sui Foundation blog website! Here is the first one: https://blog.suifoundation.org/encode-club-sui-series-1/

Good idea though, we'll add the links to the blog posts in every lesson's folder.
